version: "3"
services:
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
      - "19092:19092"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,HOSTNAME://:19092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,HOSTNAME:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,HOSTNAME://localhost:19092 #注意此ip是你的宿主机ip
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_NODE_ID=1
      # auto create topics
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    volumes:
      - ./data/broker1:/bitnami/kafka:rw
  kafka-ui:
    container_name: kafka-ui
    image: 'provectuslabs/kafka-ui:latest'
    ports:
       - '8082:8080'  # Kafka UI 的 Web 界面端口
    environment:
       - KAFKA_CLUSTERS_0_NAME=my-kafka-cluster
       - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
       - KAFKA_CLUSTERS_0_ZOOKEEPER=
       - KAFKA_CLUSTERS_0_SCHEMAREGISTRY=none  # 明确禁用 Schema Registry
       - KAFKA_CLUSTERS_0_KAFKAVERSION=3.0.0
       - DEBUG=true  # 启用调试模式以获取更多日志信息
    depends_on:
       - kafka