version: '3'
services:
  livekit:
    image: livekit/livekit-server:latest
    ports:
      - "7880:7880"
      - "39663-49663:39663-49663/udp"
      - "7881:7881"
      - "5349:5349"
      - "3478:3478/udp"
    volumes:
      - ./livekit.yaml:/etc/livekit/livekit.yaml
      - ./cert.pem:/etc/livekit/cert.pem
      - ./key.pem:/etc/livekit/key.pem